from pathlib import Path

import jax
import jax.numpy as jnp
from catan_engine.board import Board
from catan_engine.layout import BoardLayout, make_layout
from catan_engine.state import BoardState, make_board_state
from catan_engine.tile import Tile
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from .convert import EDGE_VERTICES, board_to_model
from .models import BoardModel

app = FastAPI(title="Catan Render")


def _incident_edge(vertex: int) -> int:
    """Index of some edge touching ``vertex`` (for placing a connected road)."""
    for e, (a, b) in enumerate(EDGE_VERTICES):
        if vertex in (a, b):
            return e
    raise ValueError(f"vertex {vertex} has no edges")


def _seed_demo(layout: BoardLayout, state: BoardState) -> BoardState:
    """Place a few settlements / cities / roads so state rendering is visible.

    Occupancy arrays store player + 1 (0 = empty); vertex_type 1 = settlement,
    2 = city. The robber is moved onto the desert tile.
    """
    # (vertex, player, type) — player is 0-indexed, type 1=settlement, 2=city.
    placements = [(0, 0, 1), (15, 1, 2), (33, 2, 1), (48, 3, 1)]
    vertex_owner = state.vertex_owner
    vertex_type = state.vertex_type
    edge_road = state.edge_road
    for vertex, player, kind in placements:
        vertex_owner = vertex_owner.at[0, vertex].set(player + 1)
        vertex_type = vertex_type.at[0, vertex].set(kind)
        edge_road = edge_road.at[0, _incident_edge(vertex)].set(player + 1)

    desert = int(jnp.argmax(layout.tile_resource[0] == Tile.DESERT.value))
    robber = state.robber.at[0].set(desert)

    # Give each player some cards / VP so the corner stat panels are non-empty.
    # Resources in Tile order [sheep, wheat, wood, brick, ore]; building VP
    # matches the placements above (settlement=1, city=2).
    player_resources = state.player_resources.at[0].set(
        jnp.array(
            [
                [1, 2, 0, 1, 0],
                [0, 1, 3, 0, 2],
                [2, 0, 1, 1, 0],
                [1, 1, 1, 1, 1],
            ],
            dtype=state.player_resources.dtype,
        )
    )
    dev_hand = state.dev_hand.at[0, :, 0].set(
        jnp.array([1, 0, 2, 1], dtype=state.dev_hand.dtype)
    )
    victory_points = state.victory_points.at[0].set(
        jnp.array([1, 2, 1, 1], dtype=state.victory_points.dtype)
    )
    return state._replace(
        vertex_owner=vertex_owner,
        vertex_type=vertex_type,
        edge_road=edge_road,
        robber=robber,
        player_resources=player_resources,
        dev_hand=dev_hand,
        victory_points=victory_points,
    )


def _make_board(seed: int = 0) -> Board:
    """Build a fresh, randomly-laid-out single game from the engine.

    A handful of demo placements are seeded so the renderer shows settlements,
    cities, roads and the robber alongside the tiles.
    """
    key = jax.random.key(seed)
    layout_key, state_key = jax.random.split(key)
    layout = make_layout(batch_size=1, key=layout_key)
    state = make_board_state(batch_size=1, key=state_key)
    state = _seed_demo(layout, state)
    return (layout, state)


# A board generated by the engine, served as the renderer's wire model.
_BOARD = _make_board()


@app.get("/api/board")
def get_board() -> BoardModel:
    return board_to_model(_BOARD)


# Serve built frontend when it exists (src/catan_render/server.py -> package root)
_dist = Path(__file__).parent.parent.parent / "frontend" / "dist"
if _dist.exists():
    app.mount("/", StaticFiles(directory=_dist, html=True), name="static")
