/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Create */
        post: operations["post_create_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Join */
        post: operations["post_join_api_games__game_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Action
         * @description Apply the acting seat's move; the request must prove that seat.
         */
        post: operations["post_action_api_games__game_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description Server-sent events: the requester's snapshot now, then again on
         *     every state change (moves, bot plays, chat, joins). Comment lines
         *     keep idle connections alive.
         */
        get: operations["get_events_api_games__game_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat
         * @description Append a chat message to the game log.
         */
        post: operations["post_chat_api_games__game_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description The finished game as ``catan_engine.record`` JSON -- a
         *     self-contained, replayable transcript. 409 while running: replaying a
         *     record reconstructs hidden hands, so live games don't export.
         */
        get: operations["get_record_api_games__game_id__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Replay From Game
         * @description Load a finished game for replay (409 while it is still running:
         *     replaying reconstructs hidden hands).
         */
        post: operations["post_replay_from_game_api_games__game_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Replay
         * @description Load a game record (the ``catan_engine.record`` JSON document) for
         *     replay; returns the opening state. ``422`` if the record is malformed
         *     or fails replay validation.
         */
        post: operations["post_replay_api_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Replay State
         * @description The loaded replay after ``move`` moves (0 = the opening board).
         *
         *     ``404`` when no replay is loaded; ``422`` when ``move`` is out of
         *     range.
         */
        get: operations["get_replay_state_api_replay_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Replay Record
         * @description The loaded replay's record JSON (e.g. to save it to a file).
         */
        get: operations["get_replay_record_api_replay_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bots
         * @description Bot kinds available for seats (catan-agents names), each with the
         *     player counts it supports and its configurable build parameters.
         */
        get: operations["get_bots_api_bots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionModel
         * @description One legal move for the acting player, decoded from the AEC flat action set.
         *
         *     ``flat`` is the engine's flat action index (post it back to apply the move).
         *     ``type`` is the lowercased :class:`ActionType` name. Depending on the type, at
         *     most one geometry/resource group below is populated; the rest stay ``None``.
         */
        ActionModel: {
            /** Flat */
            flat: number;
            /** Type */
            type: string;
            /** Label */
            label: string;
            vertex?: components["schemas"]["CubeModel"] | null;
            edge?: components["schemas"]["EdgeModel"] | null;
            tile?: components["schemas"]["HexModel"] | null;
            /** Victim */
            victim?: number | null;
            /** Resource */
            resource?: string | null;
            /** Resources */
            resources?: string[] | null;
            /** Give */
            give?: string | null;
            /** Receive */
            receive?: string | null;
            /** Partner */
            partner?: number | null;
        };
        /**
         * BankModel
         * @description Cards left in the supply: resource stacks plus the development deck.
         */
        BankModel: {
            resources: components["schemas"]["ResourceCounts"];
            /** Dev Cards */
            dev_cards: number;
        };
        /**
         * BeliefModel
         * @description Card counting from one human seat's perspective.
         *
         *     Everything here is derivable from public information (the engine's belief
         *     tracker), so showing it to that seat never leaks hidden state. The
         *     observer's own row is omitted — their hand is already on screen.
         */
        BeliefModel: {
            /** Observer */
            observer: number;
            /** Players */
            players: components["schemas"]["PlayerBeliefModel"][];
        };
        /** BoardModel */
        BoardModel: {
            /** Tiles */
            tiles: components["schemas"]["TileModel"][];
            /**
             * Buildings
             * @default []
             */
            buildings: components["schemas"]["BuildingModel"][];
            /**
             * Roads
             * @default []
             */
            roads: components["schemas"]["RoadModel"][];
            /**
             * Ports
             * @default []
             */
            ports: components["schemas"]["PortModel"][];
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["PlayerModel"][];
            robber?: components["schemas"]["HexModel"] | null;
            bank?: components["schemas"]["BankModel"] | null;
        };
        /**
         * BotMoveModel
         * @description One just-played bot move: the seat that acted and the decoded action.
         */
        BotMoveModel: {
            /** Player */
            player: number;
            action: components["schemas"]["ActionModel"];
        };
        /**
         * BuildingModel
         * @description A settlement or city sitting on a vertex, owned by a 0-indexed player.
         */
        BuildingModel: {
            cube: components["schemas"]["CubeModel"];
            /** Player */
            player: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "settlement" | "city";
        };
        /**
         * CubeModel
         * @description A board vertex, in the engine's cube coordinates (q + r + s = ±1).
         */
        CubeModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
            /** S */
            s: number;
        };
        /**
         * DevCardCounts
         * @description Unplayed development cards in hand, by type (DevCard order).
         */
        DevCardCounts: {
            /** Knight */
            knight: number;
            /** Road Building */
            road_building: number;
            /** Year Of Plenty */
            year_of_plenty: number;
            /** Monopoly */
            monopoly: number;
            /** Victory Point */
            victory_point: number;
        };
        /**
         * EdgeModel
         * @description A board edge between two vertices (in cube coordinates).
         */
        EdgeModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
        };
        /**
         * GameModel
         * @description One requester's snapshot: board + status + their legal moves.
         *
         *     Views are per-seat: ``your_turn`` / ``actions`` / unredacted hands /
         *     ``belief`` follow the seats the request's tokens prove.
         */
        GameModel: {
            /** Id */
            id: string;
            /**
             * Version
             * @default 0
             */
            version: number;
            board: components["schemas"]["BoardModel"];
            status: components["schemas"]["GameStatusModel"];
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ActionModel"][];
            bot_move?: components["schemas"]["BotMoveModel"] | null;
            /**
             * Log
             * @default []
             */
            log: components["schemas"]["LogEntryModel"][];
            belief?: components["schemas"]["BeliefModel"] | null;
            /**
             * Seats Claimed
             * @default []
             */
            seats_claimed: number[];
        };
        /**
         * GameStatusModel
         * @description Turn-flow snapshot for the live game.
         */
        GameStatusModel: {
            /** Phase */
            phase: string;
            /** Current Player */
            current_player: number;
            /** Acting Player */
            acting_player: number;
            /** Dice Roll */
            dice_roll: number;
            /** Has Rolled */
            has_rolled: boolean;
            /** Your Turn */
            your_turn: boolean;
            /** Terminal */
            terminal: boolean;
            /** Winner */
            winner?: number | null;
            /**
             * Seats
             * @default []
             */
            seats: string[];
            trade?: components["schemas"]["TradeOfferModel"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HexModel
         * @description An axial (pointy-top) tile coordinate.
         */
        HexModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
        };
        /**
         * LogEntryModel
         * @description One line of the game's chat / log.
         *
         *     ``player`` is the seat the line belongs to (``None``: a spectator's chat
         *     message). Move entries carry the ``action_type`` (the client maps it to an
         *     icon) and a short text (the action label, or ``"rolled N"`` for rolls).
         */
        LogEntryModel: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "move" | "chat" | "win";
            /** Player */
            player?: number | null;
            /** Action Type */
            action_type?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * PlayerBeliefModel
         * @description The observer's proven bounds on one player's hand (``lo == hi``: exact).
         */
        PlayerBeliefModel: {
            /** Player */
            player: number;
            res_lo: components["schemas"]["ResourceCounts"];
            res_hi: components["schemas"]["ResourceCounts"];
        };
        /**
         * PlayerModel
         * @description Summary stats for one (0-indexed) player.
         *
         *     The per-type breakdowns are private: the server nulls them out for every
         *     seat the requester doesn't own (counts stay public, as at a real table).
         */
        PlayerModel: {
            /** Player */
            player: number;
            /** Resource Cards */
            resource_cards: number;
            /** Dev Cards */
            dev_cards: number;
            /** Victory Points */
            victory_points: number;
            resources?: components["schemas"]["ResourceCounts"] | null;
            dev_card_types?: components["schemas"]["DevCardCounts"] | null;
        };
        /**
         * PortModel
         * @description A harbour spanning two coastal vertices.
         *
         *     ``resource`` is the resource of a 2:1 port, or ``None`` for a 3:1 general
         *     port.
         */
        PortModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
            /** Resource */
            resource: ("sheep" | "wheat" | "wood" | "brick" | "ore") | null;
        };
        /**
         * ReplayStateModel
         * @description The Replay view's snapshot after ``move`` of ``n_moves`` moves.
         *
         *     ``log`` holds the moves played up to that point (the win line appears only
         *     at the final move); ``winner`` / ``seats`` describe the whole record.
         */
        ReplayStateModel: {
            /** Move */
            move: number;
            /** N Moves */
            n_moves: number;
            board: components["schemas"]["BoardModel"];
            /**
             * Log
             * @default []
             */
            log: components["schemas"]["LogEntryModel"][];
            /** Winner */
            winner?: number | null;
            /** Seats */
            seats?: string[] | null;
        };
        /**
         * ResourceCounts
         * @description Resource cards in hand, by type (Tile resource order).
         */
        ResourceCounts: {
            /** Sheep */
            sheep: number;
            /** Wheat */
            wheat: number;
            /** Wood */
            wood: number;
            /** Brick */
            brick: number;
            /** Ore */
            ore: number;
        };
        /**
         * RoadModel
         * @description A road along an edge between two vertices, owned by a 0-indexed player.
         */
        RoadModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
            /** Player */
            player: number;
        };
        /**
         * Terrain
         * @enum {string}
         */
        Terrain: "wheat" | "sheep" | "wood" | "ore" | "brick" | "desert";
        /** TileModel */
        TileModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
            terrain: components["schemas"]["Terrain"];
            /** Number */
            number?: number | null;
        };
        /**
         * TradeOfferModel
         * @description The pending 1:1 domestic trade awaiting the partner's answer.
         */
        TradeOfferModel: {
            /** Proposer */
            proposer: number;
            /** Partner */
            partner: number;
            /** Give */
            give: string;
            /** Receive */
            receive: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** _ActionRequest */
        _ActionRequest: {
            /** Flat */
            flat: number;
        };
        /** _ChatRequest */
        _ChatRequest: {
            /** Text */
            text: string;
            /** Player */
            player?: number | null;
        };
        /** _CreateRequest */
        _CreateRequest: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * N Players
             * @default 4
             * @enum {integer}
             */
            n_players: 2 | 4;
            /**
             * Number Placement
             * @default random
             * @enum {string}
             */
            number_placement: "random" | "spiral";
            /** Seats */
            seats?: (string | components["schemas"]["_SeatSpec"])[] | null;
            /**
             * Claim
             * @default all
             * @enum {string}
             */
            claim: "all" | "first" | "none";
        };
        /**
         * _CreatedModel
         * @description A fresh game: its id and the creator's seat tokens.
         */
        _CreatedModel: {
            /** Id */
            id: string;
            /** Seats */
            seats: string[];
            /** Tokens */
            tokens: {
                [key: string]: string;
            };
        };
        /** _JoinRequest */
        _JoinRequest: {
            /** Seat */
            seat?: number | null;
        };
        /** _JoinedModel */
        _JoinedModel: {
            /** Id */
            id: string;
            /** Seat */
            seat: number;
            /** Token */
            token: string;
        };
        /**
         * _SeatSpec
         * @description A configured bot seat: its kind plus knob overrides from the catalog.
         */
        _SeatSpec: {
            /** Kind */
            kind: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number | boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_create_api_games_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Create-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_CreatedModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_join_api_games__game_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_JoinedModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_action_api_games__game_id__action_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_games__game_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_api_games__game_id__chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_games__game_id__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_replay_from_game_api_games__game_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_replay_api_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_state_api_replay_state_get: {
        parameters: {
            query?: {
                move?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_record_api_replay_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_bots_api_bots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
}
