/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preview
         * @description The board a new game would open on, for the map picker — no game is
         *     created. Terrain and ports depend only on the seed (not the placement).
         */
        get: operations["get_preview_api_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Create
         * @description Create a game, or return the caller's place in line when the server
         *     is at its concurrency cap (a ``202`` they re-POST with ``ticket``).
         *     Listing a game publicly (``listed``) requires a signed-in account.
         */
        post: operations["post_create_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Join */
        post: operations["post_join_api_games__game_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Seat
         * @description Retarget an unclaimed seat before play begins — open it for a human or
         *     turn it into a bot (the lobby owner's "fill to start" control). Any
         *     player in the game may do this; ``403`` for outsiders, ``409`` if the
         *     seat is taken or the game has started.
         */
        post: operations["post_seat_api_games__game_id__seats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Action
         * @description Apply the acting seat's move; the request must prove that seat.
         */
        post: operations["post_action_api_games__game_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description Server-sent events: the requester's snapshot now, then again on every
         *     state change (moves, bot plays, chat, joins). ``EventSourceResponse``
         *     adds the SSE framing, keepalive pings, and client-disconnect teardown.
         */
        get: operations["get_events_api_games__game_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat
         * @description Append a chat message to the game log.
         */
        post: operations["post_chat_api_games__game_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description The finished game as ``GameRecord`` JSON -- a self-contained,
         *     replayable transcript (served for past games too, rebuilt from the
         *     store). 409 while running; 404 if unknown.
         */
        get: operations["get_record_api_games__game_id__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Replay From Game
         * @description Load a finished game for replay (a past game too, rebuilt from the
         *     store). 409 while it is still running; 404 if unknown.
         */
        post: operations["post_replay_from_game_api_games__game_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Replay
         * @description Load a game record (the ``GameRecord`` JSON document) for replay;
         *     returns the opening state. ``422`` if the record is malformed or fails
         *     replay validation.
         */
        post: operations["post_replay_api_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Replay State
         * @description The loaded replay after ``move`` moves (0 = the opening board).
         *
         *     ``404`` when no replay is loaded; ``422`` when ``move`` is out of
         *     range.
         */
        get: operations["get_replay_state_api_replay_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Replay Record
         * @description The loaded replay's record JSON (e.g. to save it to a file).
         */
        get: operations["get_replay_record_api_replay_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bots
         * @description Bot kinds available for seats — one per registered bot service — each
         *     with its title, description, and the player counts it supports.
         */
        get: operations["get_bots_api_bots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bot-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bot Providers
         * @description Registered remote bot providers (admin only).
         */
        get: operations["list_bot_providers_api_admin_bot_providers_get"];
        put?: never;
        /**
         * Register Bot Provider
         * @description Register (or replace) a remote bot service by base URL; the bot it
         *     serves joins the catalog under its own name. ``400`` if it is unreachable
         *     (admin only).
         */
        post: operations["register_bot_provider_api_admin_bot_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bot-providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Bot Provider
         * @description Unregister a remote bot provider (admin only); ``404`` if unknown.
         */
        delete: operations["remove_bot_provider_api_admin_bot_providers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Games
         * @description The signed-in user's games — those still live where their account
         *     owns a seat — so they can resume on any device without a seat token.
         */
        get: operations["my_games_api_me_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My History
         * @description The signed-in user's finished games (newest first) — their seats, the
         *     winner, and the player count — each replayable / downloadable by id.
         */
        get: operations["my_history_api_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leaderboard
         * @description Every rated subject, ordered by player-count bucket then rating
         *     (best first). Public; clients split the buckets into ladders.
         */
        get: operations["leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lobby
         * @description Listed, joinable games (newest first) — each has an open human seat.
         */
        get: operations["lobby_api_lobby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchmake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matchmake
         * @description Find an Elo-matched game (bots filling the rest of the table), or return
         *     the caller's place in line to re-poll. A signed-in caller is matched on
         *     their rating; anonymous callers match at a fresh player's rating.
         */
        post: operations["matchmake_api_matchmake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Db.Login */
        post: operations["auth_db_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Db.Logout */
        post: operations["auth_db_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_users__id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionModel
         * @description One legal move for the acting player.
         *
         *     ``flat`` is the game's flat action index (post it back to apply the
         *     move). ``type`` is the lowercased action type. Depending on the type, at
         *     most one geometry/resource group below is populated; the rest stay ``None``.
         */
        ActionModel: {
            /** Flat */
            flat: number;
            /** Type */
            type: string;
            /** Label */
            label: string;
            vertex?: components["schemas"]["CubeModel"] | null;
            edge?: components["schemas"]["EdgeModel"] | null;
            tile?: components["schemas"]["HexModel"] | null;
            /** Victim */
            victim?: number | null;
            /** Resource */
            resource?: string | null;
            /** Resources */
            resources?: string[] | null;
            /** Give */
            give?: string | null;
            /** Receive */
            receive?: string | null;
            /** Partner */
            partner?: number | null;
        };
        /**
         * BankModel
         * @description Cards left in the supply: resource stacks plus the development deck.
         */
        BankModel: {
            resources: components["schemas"]["ResourceCounts"];
            /** Dev Cards */
            dev_cards: number;
        };
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /**
         * BeliefModel
         * @description Card counting from one human seat's perspective.
         *
         *     Everything here is derivable from public information (the card-counting
         *     tracker), so showing it to that seat never leaks hidden state. The
         *     observer's own row is omitted — their hand is already on screen.
         */
        BeliefModel: {
            /** Observer */
            observer: number;
            /** Players */
            players: components["schemas"]["PlayerBeliefModel"][];
        };
        /** BoardModel */
        BoardModel: {
            /** Tiles */
            tiles: components["schemas"]["TileModel"][];
            /**
             * Buildings
             * @default []
             */
            buildings: components["schemas"]["BuildingModel"][];
            /**
             * Roads
             * @default []
             */
            roads: components["schemas"]["RoadModel"][];
            /**
             * Ports
             * @default []
             */
            ports: components["schemas"]["PortModel"][];
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["PlayerModel"][];
            robber?: components["schemas"]["HexModel"] | null;
            bank?: components["schemas"]["BankModel"] | null;
        };
        /** Body_auth_db_login_api_auth_login_post */
        Body_auth_db_login_api_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BotMoveModel
         * @description One just-played bot move: the seat that acted and the decoded action.
         */
        BotMoveModel: {
            /** Player */
            player: number;
            action: components["schemas"]["ActionModel"];
        };
        /**
         * BuildingModel
         * @description A settlement or city sitting on a vertex, owned by a 0-indexed player.
         */
        BuildingModel: {
            cube: components["schemas"]["CubeModel"];
            /** Player */
            player: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "settlement" | "city";
        };
        /**
         * CubeModel
         * @description A board vertex, in cube coordinates (q + r + s = ±1).
         */
        CubeModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
            /** S */
            s: number;
        };
        /**
         * DevCardCounts
         * @description Unplayed development cards in hand, by type (DevCard order).
         */
        DevCardCounts: {
            /** Knight */
            knight: number;
            /** Road Building */
            road_building: number;
            /** Year Of Plenty */
            year_of_plenty: number;
            /** Monopoly */
            monopoly: number;
            /** Victory Point */
            victory_point: number;
        };
        /**
         * EdgeModel
         * @description A board edge between two vertices (in cube coordinates).
         */
        EdgeModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /**
         * GameModel
         * @description One requester's snapshot: board + status + their legal moves.
         *
         *     Views are per-seat: ``your_turn`` / ``actions`` / unredacted hands /
         *     ``belief`` follow the seats the request's tokens prove.
         */
        GameModel: {
            /** Id */
            id: string;
            /**
             * Version
             * @default 0
             */
            version: number;
            board: components["schemas"]["BoardModel"];
            status: components["schemas"]["GameStatusModel"];
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ActionModel"][];
            bot_move?: components["schemas"]["BotMoveModel"] | null;
            /**
             * Log
             * @default []
             */
            log: components["schemas"]["LogEntryModel"][];
            belief?: components["schemas"]["BeliefModel"] | null;
            /**
             * Seats Claimed
             * @default []
             */
            seats_claimed: number[];
            /**
             * Your Seats
             * @default []
             */
            your_seats: number[];
            /**
             * Seat Names
             * @default []
             */
            seat_names: (string | null)[];
        };
        /**
         * GameStatusModel
         * @description Turn-flow snapshot for the live game.
         */
        GameStatusModel: {
            /** Phase */
            phase: string;
            /** Current Player */
            current_player: number;
            /** Acting Player */
            acting_player: number;
            /** Dice Roll */
            dice_roll: number;
            /** Has Rolled */
            has_rolled: boolean;
            /** Your Turn */
            your_turn: boolean;
            /** Terminal */
            terminal: boolean;
            /** Winner */
            winner?: number | null;
            /**
             * Seats
             * @default []
             */
            seats: string[];
            /**
             * Victory Points To Win
             * @default 10
             */
            victory_points_to_win: number;
            trade?: components["schemas"]["TradeOfferModel"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HexModel
         * @description An axial (pointy-top) tile coordinate.
         */
        HexModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
        };
        /**
         * LogEntryModel
         * @description One line of the game's chat / log.
         *
         *     ``player`` is the seat the line belongs to (``None``: a spectator's chat
         *     message). Move entries carry the ``action_type`` (the client maps it to an
         *     icon) and a short text (the action label, or ``"rolled N"`` for rolls).
         */
        LogEntryModel: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "move" | "chat" | "win";
            /** Player */
            player?: number | null;
            /** Action Type */
            action_type?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * PlayerBeliefModel
         * @description The observer's proven bounds on one player's hand (``lo == hi``: exact).
         */
        PlayerBeliefModel: {
            /** Player */
            player: number;
            res_lo: components["schemas"]["ResourceCounts"];
            res_hi: components["schemas"]["ResourceCounts"];
        };
        /**
         * PlayerModel
         * @description Summary stats for one (0-indexed) player.
         *
         *     The per-type breakdowns are private: the server nulls them out for every
         *     seat the requester doesn't own (counts stay public, as at a real table).
         */
        PlayerModel: {
            /** Player */
            player: number;
            /** Resource Cards */
            resource_cards: number;
            /** Dev Cards */
            dev_cards: number;
            /** Victory Points */
            victory_points: number;
            /**
             * Knights Played
             * @default 0
             */
            knights_played: number;
            /**
             * Longest Road
             * @default false
             */
            longest_road: boolean;
            /**
             * Largest Army
             * @default false
             */
            largest_army: boolean;
            resources?: components["schemas"]["ResourceCounts"] | null;
            dev_card_types?: components["schemas"]["DevCardCounts"] | null;
        };
        /**
         * PortModel
         * @description A harbour spanning two coastal vertices.
         *
         *     ``resource`` is the resource of a 2:1 port, or ``None`` for a 3:1 general
         *     port.
         */
        PortModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
            /** Resource */
            resource: ("sheep" | "wheat" | "wood" | "brick" | "ore") | null;
        };
        /**
         * ReplayStateModel
         * @description The Replay view's snapshot after ``move`` of ``n_moves`` moves.
         *
         *     ``log`` holds the moves played up to that point (the win line appears only
         *     at the final move); ``winner`` / ``seats`` describe the whole record.
         */
        ReplayStateModel: {
            /** Move */
            move: number;
            /** N Moves */
            n_moves: number;
            board: components["schemas"]["BoardModel"];
            /**
             * Log
             * @default []
             */
            log: components["schemas"]["LogEntryModel"][];
            /** Winner */
            winner?: number | null;
            /** Seats */
            seats?: string[] | null;
        };
        /**
         * ResourceCounts
         * @description Resource cards in hand, by type (Tile resource order).
         */
        ResourceCounts: {
            /** Sheep */
            sheep: number;
            /** Wheat */
            wheat: number;
            /** Wood */
            wood: number;
            /** Brick */
            brick: number;
            /** Ore */
            ore: number;
        };
        /**
         * RoadModel
         * @description A road along an edge between two vertices, owned by a 0-indexed player.
         */
        RoadModel: {
            a: components["schemas"]["CubeModel"];
            b: components["schemas"]["CubeModel"];
            /** Player */
            player: number;
        };
        /**
         * Terrain
         * @enum {string}
         */
        Terrain: "wheat" | "sheep" | "wood" | "ore" | "brick" | "desert";
        /** TileModel */
        TileModel: {
            /** Q */
            q: number;
            /** R */
            r: number;
            terrain: components["schemas"]["Terrain"];
            /** Number */
            number?: number | null;
        };
        /**
         * TradeOfferModel
         * @description The pending 1:1 domestic trade awaiting the partner's answer.
         */
        TradeOfferModel: {
            /** Proposer */
            proposer: number;
            /** Partner */
            partner: number;
            /** Give */
            give: string;
            /** Receive */
            receive: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Password */
            password?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** _ActionRequest */
        _ActionRequest: {
            /** Flat */
            flat: number;
        };
        /** _ChatRequest */
        _ChatRequest: {
            /** Text */
            text: string;
            /** Player */
            player?: number | null;
        };
        /** _CreateRequest */
        _CreateRequest: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * N Players
             * @default 4
             * @enum {integer}
             */
            n_players: 2 | 4;
            /**
             * Number Placement
             * @default random
             * @enum {string}
             */
            number_placement: "random" | "spiral";
            /** Seats */
            seats?: string[] | null;
            /**
             * Claim
             * @default all
             * @enum {string}
             */
            claim: "all" | "first" | "none";
            /**
             * Listed
             * @default false
             */
            listed: boolean;
            /** Ticket */
            ticket?: string | null;
        };
        /**
         * _CreatedModel
         * @description A fresh game: its id and the creator's seat tokens.
         */
        _CreatedModel: {
            /** Id */
            id: string;
            /** Seats */
            seats: string[];
            /** Tokens */
            tokens: {
                [key: string]: string;
            };
        };
        /** _JoinRequest */
        _JoinRequest: {
            /** Seat */
            seat?: number | null;
        };
        /** _JoinedModel */
        _JoinedModel: {
            /** Id */
            id: string;
            /** Seat */
            seat: number;
            /** Token */
            token: string;
        };
        /**
         * _LeaderboardEntry
         * @description One ranked subject in a player-count bucket.
         */
        _LeaderboardEntry: {
            /** N Players */
            n_players: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Rating */
            rating: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
        };
        /**
         * _LobbyGameModel
         * @description One joinable game in the lobby.
         */
        _LobbyGameModel: {
            /** Id */
            id: string;
            /** N Players */
            n_players: number;
            /** Number Placement */
            number_placement: string;
            /** Seats */
            seats: string[];
            /** Claimed */
            claimed: number[];
            /** Open Seats */
            open_seats: number;
            /** Created At */
            created_at: number;
        };
        /**
         * _MatchFound
         * @description Matched: the seat claimed for the caller in a freshly created game.
         */
        _MatchFound: {
            /** Id */
            id: string;
            /** Seat */
            seat: number;
            /** Token */
            token: string;
        };
        /**
         * _MatchQueued
         * @description Still finding a game: re-POST with ``ticket`` until matched.
         */
        _MatchQueued: {
            /**
             * Queued
             * @default true
             * @constant
             */
            queued: true;
            /** Ticket */
            ticket: string;
            /** Waiting */
            waiting: number;
        };
        /** _MatchRequest */
        _MatchRequest: {
            /**
             * N Players
             * @default 2
             * @enum {integer}
             */
            n_players: 2 | 4;
            /** Ticket */
            ticket?: string | null;
        };
        /**
         * _MyGameModel
         * @description A live game the signed-in user owns a seat in.
         */
        _MyGameModel: {
            /** Id */
            id: string;
            /** Seats */
            seats: number[];
        };
        /**
         * _PastGameModel
         * @description A finished game in the user's history.
         */
        _PastGameModel: {
            /** Id */
            id: string;
            /** Seats */
            seats: number[];
            /** N Players */
            n_players: number;
            /** Winner */
            winner: number | null;
            /** Finished At */
            finished_at: number;
        };
        /**
         * _ProviderRequest
         * @description A remote bot service to register: its base URL (the bot self-identifies).
         */
        _ProviderRequest: {
            /** Base Url */
            base_url: string;
        };
        /**
         * _QueuedModel
         * @description The server is at its concurrency cap: the caller's place in line. They
         *     re-POST with ``ticket`` until they get a :class:`_CreatedModel` back.
         */
        _QueuedModel: {
            /**
             * Queued
             * @default true
             * @constant
             */
            queued: true;
            /** Ticket */
            ticket: string;
            /** Position */
            position: number;
            /** Total */
            total: number;
        };
        /** _SeatRequest */
        _SeatRequest: {
            /** Seat */
            seat: number;
            /** Kind */
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_preview_api_preview_get: {
        parameters: {
            query?: {
                seed?: number;
                n_players?: number;
                number_placement?: "random" | "spiral";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_create_api_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_CreatedModel"] | components["schemas"]["_QueuedModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_join_api_games__game_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_JoinedModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_seat_api_games__game_id__seats_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_SeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_action_api_games__game_id__action_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_games__game_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_api_games__game_id__chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Tokens"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_games__game_id__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_replay_from_game_api_games__game_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_replay_api_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_state_api_replay_state_get: {
        parameters: {
            query?: {
                move?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayStateModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_record_api_replay_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_bots_api_bots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    list_bot_providers_api_admin_bot_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    register_bot_provider_api_admin_bot_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_bot_provider_api_admin_bot_providers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_games_api_me_games_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_MyGameModel"][];
                };
            };
        };
    };
    my_history_api_me_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_PastGameModel"][];
                };
            };
        };
    };
    leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_LeaderboardEntry"][];
                };
            };
        };
    };
    lobby_api_lobby_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_LobbyGameModel"][];
                };
            };
        };
    };
    matchmake_api_matchmake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_MatchQueued"] | components["schemas"]["_MatchFound"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_db_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_db_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
                     *       "token_type": "bearer"
                     *     }
                     */
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_db_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
